export class UserData{
    constructor(fn,ln,dob,username,password,generatedEmail,generatedPassword){
        this.firstname = fn;
        this.lastname = ln;
        this.dateOfBirth = dob;

        //User signs up and sign in with this
        this.firebaseUsername = username;
        this.firebasePassword = password;

        //Autogenerated email and password for user email feature
        this.cpanelGeneratedEmail = generatedEmail;
        this.cpanelGeneratedPassword = generatedPassword;
    }
}